spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sgcc_v3
    username: sgcc_user
    password: sgcc_password
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true

#logging:
  #level:
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql: TRACE

security:
  systemId: 1
  apiKey: uLCMTMdPOcdy4HTag9GpSTLSJAovBEFgbGrQR6R2fkMXL2mtKeyDRqi8lNOb5ar1fLN7HZGPttqtNZ5h4Vf8WmQuJinAqnWAqfNyNhPCVDN2xCkUFtGnkqO88vQz6HUr
  jwt:
    secret: "u6F1v9Hq4pRZ2eK1tGWs7C9qDb48NdP7u1Qx3Ls8UPI="
    expiration: 3600
